os: linux

language: go

go:
  - 1.16.x

services:
  - postgresql

env:
  - APP_DB_USERNAME="postgres" APP_DB_PASSWORD="" APP_DB_NAME="postgres"

script:
  # Build
  - cd src && go build -v

  # Test
  - cd src && go test -v
